services:
  cassandra1:
    image: cassandra:5.0.6
    container_name: cassandra1
    ports:
      - "9042:9042"
    environment:
      - CASSANDRA_CLUSTER_NAME=rag_cluster
      - CASSANDRA_DC=dc1
      - CASSANDRA_RACK=rack1
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_SEEDS=cassandra1 
      - MAX_HEAP_SIZE=512M
      - HEAP_NEWSIZE=128M
    volumes:
      - cassandra1_data:/var/lib/cassandra

  cassandra2:
    image: cassandra:5.0.6
    container_name: cassandra2
    depends_on:
      - cassandra1
    ports:
      - "9043:9042" 
    environment:
      - CASSANDRA_CLUSTER_NAME=rag_cluster
      - CASSANDRA_DC=dc1
      - CASSANDRA_RACK=rack1
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_SEEDS=cassandra1 
      - MAX_HEAP_SIZE=512M
      - HEAP_NEWSIZE=128M
    volumes:
      - cassandra2_data:/var/lib/cassandra

volumes:
  cassandra1_data:
  cassandra2_data: